name: vehicle_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Pure Dart Database (No SQLite C++ errors!)
  sembast: ^3.7.1
  path_provider: ^2.1.2

  # State Management
  flutter_riverpod: ^2.5.1

  # Utilities
  intl: ^0.19.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3

  # ... other deps
  file_picker: ^8.0.0
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  archive: ^3.6.1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # Support modern Android adaptive icons
  adaptive_icon_background: "#ffffff" # White background
  adaptive_icon_foreground: "assets/icon.png"